USE adlister_db;

TRUNCATE ads;

INSERT INTO ads (user_id,
                category_id,
                title,
                description,
                listed_on,
                country,
                location,
                city,
                zip_code,
                classified_status_id,
                price_type_id,
                price)
VALUES (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        45103,
        1,
        1,
        120.25),
       (1,
        7,
        'Baby Clothes',
        'Great deal on clothes! Our child just outgrew them.',
        CURRENT_TIMESTAMP,
        'United States',
        '8286 Tower Lane',
        'San Antonio',
        48823,
        1,
        2,
        50.00),
       (1,
        8,
        'Harry Potter and the Sorcerers Stone',
        'First edition Harry Potter book, get now while still available!',
        CURRENT_TIMESTAMP,
        'United States',
        '17 Elmwood Rd.',
        'San Antonio',
        31525,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        60201,
        1,
        1,
        120.25),
       (1,
        2,
        'Ps4 and games',
        'Great list of games and barely used ps4',
        CURRENT_TIMESTAMP,
        'United States',
        '351 Mayflower St.',
        'San Antonio',
        70806,
        1,
        1,
        120),
       (1,
        9,
        '60 in 4k flatscreen tv',
        'An amazing tv, have had nothing but great experiences with. Nothing wrong, just got a new tv for superbowl ano not need  this one anymore',
        CURRENT_TIMESTAMP,
        'United States',
        '33 Canterbury Street',
        'San Antonio',
        12601,
        1,
        1,
        300),
       (1,
        9,
        'Alienware labtop',
        'Do not need this labtop anymore, ',
        CURRENT_TIMESTAMP,
        'United States',
        '132 Myrtle Street',
        'San Antonio',
        30736,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),
       (1,
        9,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        'United States',
        '1234 Broad Street',
        'San Antonio',
        12345,
        1,
        1,
        120.25),

       (1,
        13,
        'Woodland Shoes GB2271116',
        'Brown Leather Boots',
        CURRENT_TIMESTAMP,
        'United States',
        '11738 West Hollywood Blvd',
        'San Antonio',
        78230,
        1,
        1,
        3500.45);