USE adlister_db;

TRUNCATE ads;

INSERT INTO ads (user_id,
                category_id,
                title,
                description,
                listed_on,
                location,
                city,
                zip_code,
                classified_status_id,
                price_type_id,
                price,
                image)
VALUES (1,
        17,
        'Canon EOS 7D 18MP CMOS Digital SLR',
        'The new EOS 7D represents a whole new class of camera, with a host of brand new features designed to enhance every facet of the photographic process, from still images to video.',
        CURRENT_TIMESTAMP,
        '1234 Broad Street',
        'San Antonio',
        45103,
        1,
        1,
        120.25,
        'http://loremflickr.com/320/240/dog'),

       (2,
        15,
        'Baby Clothes',
        'Great deal on clothes! Our child just outgrew them.',
        CURRENT_TIMESTAMP,
        '8286 Tower Lane',
        'San Antonio',
        48823,
        1,
        2,
        50.00,
        'http://loremflickr.com/320/240/dog'),

       (3,
        16,
        'Harry Potter and the Sorcerers Stone',
        'First edition Harry Potter book, get now while still available!',
        CURRENT_TIMESTAMP,
        '17 Elmwood Rd.',
        'San Antonio',
        31525,
        1,
        1,
        120.25,
        'http://loremflickr.com/320/240/dog'),

       (4,
        12,
        'Ps4 and games',
        'Great list of games and barely used ps4',
        CURRENT_TIMESTAMP,
        '351 Mayflower St.',
        'San Antonio',
        70806,
        1,
        1,
        120,
        'http://loremflickr.com/320/240/dog'),

       (5,
        6,
        '60 in 4k flatscreen tv',
        'An amazing tv, have had nothing but great experiences with. Nothing wrong, just got a new tv for superbowl ano not need  this one anymore',
        CURRENT_TIMESTAMP,
        '33 Canterbury Street',
        'San Antonio',
        12601,
        1,
        1,
        300,
        'http://loremflickr.com/320/240/dog'),

       (1,
        20,
        'Alienware labtop',
        'Do not need this labtop anymore, ',
        CURRENT_TIMESTAMP,
        '132 Myrtle Street',
        'San Antonio',
        30736,
        1,
        1,
        120.25,
        'http://loremflickr.com/320/240/dog'),

       (2,
        21,
        'Woodland Shoes GB2271116',
        'Brown Leather Boots',
        CURRENT_TIMESTAMP,
        '11738 West Hollywood Blvd',
        'San Antonio',
        78230,
        1,
        1,
        3500.45,
        'http://loremflickr.com/320/240/dog'),

#        ==========================================

       (5,
        23,
        'Adjustable Drafting Table Art & Craft Station Drawing Desk Folding w/ Side Tray',
        'This is our latest drawing desk which is durable, high quality and heavy duty. With adjustable design, you can adjust the angle of desktop according to your personal need, such as reading, writing, drawing and so on. And also it will help you reduce back pain and keep better posture a lot. This drawing desk will surely bring you a lot of enjoyment in your leisure time or your study time. Don''t hesitate to buy one!',
        CURRENT_TIMESTAMP,
        '2319 West Fork Drive',
        'San Antonio',
        33009,
        1,
        1,
        69.99,
        'https://i.ebayimg.com/images/g/KJUAAOSwQFNbD2x~/s-l1600.jpg'),

       (4,
        23,
        '19" LED Artist Stencil Board Tattoo Drawing Tracing Table Display Light Box Pad',
        'Applications：Perfect tool for animations, cartoons, stencils, tattoos, drawings, arts and crafts, photograph, film, slider transferring, professional tracing in architecture, design and drawing. Humanized Design：84 leds strong back light, 360 degree rotating pad to adjust angle, 7 stages height adjustable pad to meet different height, Measuring border to quickly scale your work, Binder clip to hold the tracing paper firmly, Anti-skid feet to keep the led board steady.',
        CURRENT_TIMESTAMP,
        '1989 Hazelwood Avenue',
        'San Antonio',
        50266,
        1,
        1,
        46.94,
        'https://i.ebayimg.com/images/g/kTUAAOSwN~paA4VV/s-l1600.jpg'),

       (3,
        24,
        'Bob Ross Liquid White Medium 16 oz Bottle Oil Paint Base Coat',
        'Bob''s unique secret formula of base coats aid in the painting''s foundation and keep the canvas wet, the most fundamental step in Bob''s wet-on-wet technique. Smooth and slow drying, they allow blending and mixing right on the canvas! Non-Toxic.',
        CURRENT_TIMESTAMP,
        '673 Rardin Drive',
        'San Antonio',
        94301,
        1,
        1,
        21.96,
        'https://i.ebayimg.com/images/g/9scAAOSwTi1bbZOY/s-l1600.jpg'),

       (2,
        24,
        'Angelus Brand Acrylic Leather Vinyl Waterproof Paint Color Chart #720 Collection',
        'Angelus Acrylic  Leather Paints are Brilliant in Color and are used for Decorating, Staining, or Edging smooth Leather and Vinyl articles. Many Artists use  Angelus Acrylic Paint to Customize Nike Brand Shoes and other "Kicks". Angelus Leather Paint, when Dry, will not Peel, Crack, or Rub-Off. Water  based for easy clean up, also keep in mind because it is water based it is freezable.',
        CURRENT_TIMESTAMP,
        '1727 Hide A Way Road',
        'San Antonio',
        32801,
        1,
        1,
        4.95,
        'https://i.ebayimg.com/images/g/uY8AAOSwhOVXdaKi/s-l1600.jpg'),

       (1,
        25,
        'Electric Scooter Widewheel Folding Dual Motor Mercane Kick E-Scooter',
        'The electric scooter is more compact than motorcycle but equipped with its wheels powered by electricity like motorcycle. So, it is getting increasingly popular and leads the personal mobility market these days. Because it is portable and easy to carryaround cities or store in your car trunk. But, if you had the experience to ride the electric scooter, you would probably feel less riding comfort especially because of smaller wheels compared with ones of motorcycles. So, we decided to create something not only great to ride but pack electric mobility. You no longer have to give up comfortable ride for the portable feature you want.',
        CURRENT_TIMESTAMP,
        '2355 Griffin Street',
        'San Antonio',
        85012,
        1,
        1,
        999.00,
        'https://i.ebayimg.com/images/g/39AAAOSwIs1cCdJr/s-l1600.jpg'),

       (5,
        25,
        'Self Balancing Scooter Hoverboard UL2272 w/ Bluetooth Speaker/LED Light',
        'This UL balance supports electrical and fire-safety testing and certification under UL 2272, Electrical Systems for Self-Balancing Scooters. This standard evaluates the safety of the electrical drive train system and battery and charger system combinations are all uL listed for fireproof safety. We strive to make identifying a UL Certified product as easy as possible. Simply look for the UL Mark for self-balancing scooters on the front of the packaging and the UL holographic certification label with the Enhanced Mark on the bottom of the product. This label is your indication that you have a genuine UL Certified product.',
        CURRENT_TIMESTAMP,
        '242 Spinnaker Lane',
        'San Antonio',
        61315,
        1,
        1,
        119.54,
        'https://i.ebayimg.com/images/g/NzUAAOSwHF5cZyBe/s-l1600.jpg'),

       (4,
        26,
        '20" Electric Fat Tire Bike Snow Mountain Bicycle w Removable Lithium Battery 48V',
        'This is our brand new and high quality electric mountain bike. Turning e-Bike riders into explorers and adventurers, the powerful drive provides the right power at the right moment. The result: even more fun while riding an e-Bike. The performance Line is designed for athletic and powerful riding. From flat to steep, asphalt to trail -- the Drive Unit invariably masters every style of riding. Superior engine thoroughly engineered the drive system with powerful electronics and a low-vibration motor, while maintaining low volume and weight. This additional power is incredibly smooth, providing a unique riding experience. Don''t hesitate to begin your exploration!',
        CURRENT_TIMESTAMP,
        '2314 Orphan Road',
        'San Antonio',
        14701,
        1,
        1,
        859.99,
        'https://i.ebayimg.com/images/g/n0oAAOSwbw1aIOuo/s-l1600.jpg'),

       (3,
        26,
        'Electric Adults Tricycle 20’’ Fat Tire LCD Display 500W Motor Lithium Battery',
        'Our electric tricycle has strong frame, durable tire and powerful motor. The mechanical front and rear disc-brake design and LED headlight and backlight give smooth and safe ride. The 500W motor, 48V/10AH lithium battery, and 20’’ fat tire provide you with better riding experience. This tricycle also has a large rear basket which is perfect for picnics, storing your groceries or giving your pet a ride. Our electric tricycle will be your great choice.',
        CURRENT_TIMESTAMP,
        '4791 Chicago Avenue',
        'San Antonio',
        93721,
        1,
        1,
        1549.99,
        'https://i.ebayimg.com/images/g/iF4AAOSw0d1cD39j/s-l1600.jpg');

#        ==========================================
